<?php
namespace Tasks\ContactBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

}