#ContactUs form routers
tasks_contact:
    path:     /
    defaults: { _controller: TasksContactBundle:ContactUs:contact }
    requirements:
            _method:  GET
tasks_success:
    path:     /
    defaults: { _controller: TasksContactBundle:ContactUs:contact }
    requirements:
            _method:  POST

#CRUD routers

tasks_contact_messages:
    path:     /messages
    defaults: { _controller: TasksContactBundle:Message:index }

tasks_contact_message_create:
    path:     /message_create
    defaults: { _controller: TasksContactBundle:Message:create }

tasks_contact_message_delete:
    path:     /message_delete/{id}
    defaults: { _controller: TasksContactBundle:Message:delete }

tasks_contact_message_update:
    path:     /message_update/{id}
    defaults: { _controller: TasksContactBundle:Message:update }

tasks_contact_message_edit:
    path:     /message_edit/{id}
    defaults: { _controller: TasksContactBundle:Message:edit }

tasks_contact_message_show:
    path:     /message_show/{id}
    defaults: { _controller: TasksContactBundle:Message:show }

tasks_contact_message_new:
    path:     /message_new
    defaults: { _controller: TasksContactBundle:Message:new }